// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.3.
// **********************************************************************

#ifndef __PATCH_H_
#define __PATCH_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace tars
{
    using namespace std;
    struct FileInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.FileInfo";
        }
        static string MD5()
        {
            return "6c7679ddfd0048dbd9c8d8084bfd53c0";
        }
        FileInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            path = "";
            size = 0;
            canExec = true;
            md5 = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(path, 0);
            _os.write(size, 1);
            _os.write(canExec, 2);
            if (md5 != "")
            {
                _os.write(md5, 3);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(path, 0, true);
            _is.read(size, 1, true);
            _is.read(canExec, 2, true);
            _is.read(md5, 3, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["path"] = tars::JsonOutput::writeJson(path);
            p->value["size"] = tars::JsonOutput::writeJson(size);
            p->value["canExec"] = tars::JsonOutput::writeJson(canExec);
            p->value["md5"] = tars::JsonOutput::writeJson(md5);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(path,pObj->value["path"], true);
            tars::JsonInput::readJson(size,pObj->value["size"], true);
            tars::JsonInput::readJson(canExec,pObj->value["canExec"], true);
            tars::JsonInput::readJson(md5,pObj->value["md5"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(path,"path");
            _ds.display(size,"size");
            _ds.display(canExec,"canExec");
            _ds.display(md5,"md5");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(path, true);
            _ds.displaySimple(size, true);
            _ds.displaySimple(canExec, true);
            _ds.displaySimple(md5, false);
            return _os;
        }
    public:
        std::string path;
        tars::Int32 size;
        tars::Bool canExec;
        std::string md5;
    };
    inline bool operator==(const FileInfo&l, const FileInfo&r)
    {
        return l.path == r.path && l.size == r.size && l.canExec == r.canExec && l.md5 == r.md5;
    }
    inline bool operator!=(const FileInfo&l, const FileInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const FileInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,FileInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct FileContent : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.FileContent";
        }
        static string MD5()
        {
            return "54f4e86947d5a4ec3cc8741289290a28";
        }
        FileContent()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            md5 = "";
            name = "";
            firstChunk = true;
            lastChunk = true;
            content.clear();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(md5, 0);
            _os.write(name, 1);
            _os.write(firstChunk, 2);
            _os.write(lastChunk, 3);
            _os.write(content, 4);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(md5, 0, true);
            _is.read(name, 1, true);
            _is.read(firstChunk, 2, true);
            _is.read(lastChunk, 3, true);
            _is.read(content, 4, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["md5"] = tars::JsonOutput::writeJson(md5);
            p->value["name"] = tars::JsonOutput::writeJson(name);
            p->value["firstChunk"] = tars::JsonOutput::writeJson(firstChunk);
            p->value["lastChunk"] = tars::JsonOutput::writeJson(lastChunk);
            p->value["content"] = tars::JsonOutput::writeJson(content);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(md5,pObj->value["md5"], true);
            tars::JsonInput::readJson(name,pObj->value["name"], true);
            tars::JsonInput::readJson(firstChunk,pObj->value["firstChunk"], true);
            tars::JsonInput::readJson(lastChunk,pObj->value["lastChunk"], true);
            tars::JsonInput::readJson(content,pObj->value["content"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(md5,"md5");
            _ds.display(name,"name");
            _ds.display(firstChunk,"firstChunk");
            _ds.display(lastChunk,"lastChunk");
            _ds.display(content,"content");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(md5, true);
            _ds.displaySimple(name, true);
            _ds.displaySimple(firstChunk, true);
            _ds.displaySimple(lastChunk, true);
            _ds.displaySimple(content, false);
            return _os;
        }
    public:
        std::string md5;
        std::string name;
        tars::Bool firstChunk;
        tars::Bool lastChunk;
        vector<tars::Char> content;
    };
    inline bool operator==(const FileContent&l, const FileContent&r)
    {
        return l.md5 == r.md5 && l.name == r.name && l.firstChunk == r.firstChunk && l.lastChunk == r.lastChunk && l.content == r.content;
    }
    inline bool operator!=(const FileContent&l, const FileContent&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const FileContent&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,FileContent&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


    /* callback of async proxy for client */
    class PatchPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~PatchPrxCallback(){}
        virtual void callback_deletePatchFile(tars::Int32 ret)
        { throw std::runtime_error("callback_deletePatchFile() override incorrect."); }
        virtual void callback_deletePatchFile_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_deletePatchFile_exception() override incorrect."); }

        virtual void callback_download(tars::Int32 ret,  const vector<tars::Char>& vb)
        { throw std::runtime_error("callback_download() override incorrect."); }
        virtual void callback_download_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_download_exception() override incorrect."); }

        virtual void callback_listFileInfo(tars::Int32 ret,  const vector<tars::FileInfo>& vf)
        { throw std::runtime_error("callback_listFileInfo() override incorrect."); }
        virtual void callback_listFileInfo_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_listFileInfo_exception() override incorrect."); }

        virtual void callback_preparePatchFile(tars::Int32 ret,  const std::string& result)
        { throw std::runtime_error("callback_preparePatchFile() override incorrect."); }
        virtual void callback_preparePatchFile_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_preparePatchFile_exception() override incorrect."); }

        virtual void callback_upload(tars::Int32 ret)
        { throw std::runtime_error("callback_upload() override incorrect."); }
        virtual void callback_upload_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_upload_exception() override incorrect."); }

    public:
        virtual const std::map<std::string, std::string> & getResponseContext() const
        {
            tars::CallbackThreadData * pCbtd = tars::CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw tars::TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Patch_all[]=
            {
                "deletePatchFile",
                "download",
                "listFileInfo",
                "preparePatchFile",
                "upload"
            };
            std::pair<std::string*, std::string*> r = equal_range(__Patch_all, __Patch_all+5, std::string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Patch_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_deletePatchFile_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    tars::CallbackThreadData * pCbtd = tars::CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_deletePatchFile(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_download_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<tars::Char> vb;
                    _is.read(vb, 3, true);
                    tars::CallbackThreadData * pCbtd = tars::CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_download(_ret, vb);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_listFileInfo_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<tars::FileInfo> vf;
                    _is.read(vf, 2, true);
                    tars::CallbackThreadData * pCbtd = tars::CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_listFileInfo(_ret, vf);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_preparePatchFile_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    std::string result;
                    _is.read(result, 4, true);
                    tars::CallbackThreadData * pCbtd = tars::CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_preparePatchFile(_ret, result);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_upload_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    tars::CallbackThreadData * pCbtd = tars::CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_upload(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<PatchPrxCallback> PatchPrxCallbackPtr;

    //callback of promise async proxy for client
    class PatchPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~PatchPrxCallbackPromise(){}
    public:
        struct PromisedeletePatchFile: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            std::map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< PatchPrxCallbackPromise::PromisedeletePatchFile > PromisedeletePatchFilePtr;

        PatchPrxCallbackPromise(const tars::Promise< PatchPrxCallbackPromise::PromisedeletePatchFilePtr > &promise)
        : _promise_deletePatchFile(promise)
        {}
        
        virtual void callback_deletePatchFile(const PatchPrxCallbackPromise::PromisedeletePatchFilePtr &ptr)
        {
            _promise_deletePatchFile.setValue(ptr);
        }
        virtual void callback_deletePatchFile_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:deletePatchFile_exception|Ret:";
            str += tars::TC_Common::tostr(ret);
            _promise_deletePatchFile.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< PatchPrxCallbackPromise::PromisedeletePatchFilePtr > _promise_deletePatchFile;

    public:
        struct Promisedownload: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<tars::Char> vb;
            std::map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< PatchPrxCallbackPromise::Promisedownload > PromisedownloadPtr;

        PatchPrxCallbackPromise(const tars::Promise< PatchPrxCallbackPromise::PromisedownloadPtr > &promise)
        : _promise_download(promise)
        {}
        
        virtual void callback_download(const PatchPrxCallbackPromise::PromisedownloadPtr &ptr)
        {
            _promise_download.setValue(ptr);
        }
        virtual void callback_download_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:download_exception|Ret:";
            str += tars::TC_Common::tostr(ret);
            _promise_download.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< PatchPrxCallbackPromise::PromisedownloadPtr > _promise_download;

    public:
        struct PromiselistFileInfo: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<tars::FileInfo> vf;
            std::map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< PatchPrxCallbackPromise::PromiselistFileInfo > PromiselistFileInfoPtr;

        PatchPrxCallbackPromise(const tars::Promise< PatchPrxCallbackPromise::PromiselistFileInfoPtr > &promise)
        : _promise_listFileInfo(promise)
        {}
        
        virtual void callback_listFileInfo(const PatchPrxCallbackPromise::PromiselistFileInfoPtr &ptr)
        {
            _promise_listFileInfo.setValue(ptr);
        }
        virtual void callback_listFileInfo_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:listFileInfo_exception|Ret:";
            str += tars::TC_Common::tostr(ret);
            _promise_listFileInfo.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< PatchPrxCallbackPromise::PromiselistFileInfoPtr > _promise_listFileInfo;

    public:
        struct PromisepreparePatchFile: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            std::string result;
            std::map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< PatchPrxCallbackPromise::PromisepreparePatchFile > PromisepreparePatchFilePtr;

        PatchPrxCallbackPromise(const tars::Promise< PatchPrxCallbackPromise::PromisepreparePatchFilePtr > &promise)
        : _promise_preparePatchFile(promise)
        {}
        
        virtual void callback_preparePatchFile(const PatchPrxCallbackPromise::PromisepreparePatchFilePtr &ptr)
        {
            _promise_preparePatchFile.setValue(ptr);
        }
        virtual void callback_preparePatchFile_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:preparePatchFile_exception|Ret:";
            str += tars::TC_Common::tostr(ret);
            _promise_preparePatchFile.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< PatchPrxCallbackPromise::PromisepreparePatchFilePtr > _promise_preparePatchFile;

    public:
        struct Promiseupload: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            std::map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< PatchPrxCallbackPromise::Promiseupload > PromiseuploadPtr;

        PatchPrxCallbackPromise(const tars::Promise< PatchPrxCallbackPromise::PromiseuploadPtr > &promise)
        : _promise_upload(promise)
        {}
        
        virtual void callback_upload(const PatchPrxCallbackPromise::PromiseuploadPtr &ptr)
        {
            _promise_upload.setValue(ptr);
        }
        virtual void callback_upload_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:upload_exception|Ret:";
            str += tars::TC_Common::tostr(ret);
            _promise_upload.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< PatchPrxCallbackPromise::PromiseuploadPtr > _promise_upload;

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Patch_all[]=
            {
                "deletePatchFile",
                "download",
                "listFileInfo",
                "preparePatchFile",
                "upload"
            };

            std::pair<std::string*, std::string*> r = equal_range(__Patch_all, __Patch_all+5, std::string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Patch_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_deletePatchFile_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    PatchPrxCallbackPromise::PromisedeletePatchFilePtr ptr = new PatchPrxCallbackPromise::PromisedeletePatchFile();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_deletePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_deletePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_deletePatchFile(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_download_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    PatchPrxCallbackPromise::PromisedownloadPtr ptr = new PatchPrxCallbackPromise::Promisedownload();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->vb, 3, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_download_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_download_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_download(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_listFileInfo_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    PatchPrxCallbackPromise::PromiselistFileInfoPtr ptr = new PatchPrxCallbackPromise::PromiselistFileInfo();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->vf, 2, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_listFileInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_listFileInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_listFileInfo(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_preparePatchFile_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    PatchPrxCallbackPromise::PromisepreparePatchFilePtr ptr = new PatchPrxCallbackPromise::PromisepreparePatchFile();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->result, 4, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_preparePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_preparePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_preparePatchFile(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_upload_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    PatchPrxCallbackPromise::PromiseuploadPtr ptr = new PatchPrxCallbackPromise::Promiseupload();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_upload_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_upload_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_upload(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<PatchPrxCallbackPromise> PatchPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class PatchCoroPrxCallback: public PatchPrxCallback
    {
    public:
        virtual ~PatchCoroPrxCallback(){}
    public:
        virtual const std::map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const std::map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Patch_all[]=
            {
                "deletePatchFile",
                "download",
                "listFileInfo",
                "preparePatchFile",
                "upload"
            };

            std::pair<std::string*, std::string*> r = equal_range(__Patch_all, __Patch_all+5, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Patch_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_deletePatchFile_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response->context);

                        callback_deletePatchFile(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_deletePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_deletePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_download_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<tars::Char> vb;
                        _is.read(vb, 3, true);
                        setResponseContext(msg->response->context);

                        callback_download(_ret, vb);

                    }
                    catch(std::exception &ex)
                    {
                        callback_download_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_download_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_listFileInfo_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<tars::FileInfo> vf;
                        _is.read(vf, 2, true);
                        setResponseContext(msg->response->context);

                        callback_listFileInfo(_ret, vf);

                    }
                    catch(std::exception &ex)
                    {
                        callback_listFileInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_listFileInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_preparePatchFile_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        std::string result;
                        _is.read(result, 4, true);
                        setResponseContext(msg->response->context);

                        callback_preparePatchFile(_ret, result);

                    }
                    catch(std::exception &ex)
                    {
                        callback_preparePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_preparePatchFile_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_upload_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response->context);

                        callback_upload(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_upload_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_upload_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<PatchCoroPrxCallback> PatchCoroPrxCallbackPtr;

    /* proxy for client */
    class PatchProxy : public tars::ServantProxy
    {
    public:
        typedef std::map<std::string, std::string> TARS_CONTEXT;
        tars::Int32 deletePatchFile(const std::string & app,const std::string & serverName,const std::string & patchFile,const std::map<std::string, std::string> &context = TARS_CONTEXT(),map<std::string, std::string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<std::string, std::string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"deletePatchFile", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_deletePatchFile(PatchPrxCallbackPtr callback,const std::string &app,const std::string &serverName,const std::string &patchFile,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"deletePatchFile", _os, context, _mStatus, callback);
        }
        
        tars::Future< PatchPrxCallbackPromise::PromisedeletePatchFilePtr > promise_async_deletePatchFile(const std::string &app,const std::string &serverName,const std::string &patchFile,const std::map<std::string, std::string>& context)
        {
            tars::Promise< PatchPrxCallbackPromise::PromisedeletePatchFilePtr > promise;
            PatchPrxCallbackPromisePtr callback = new PatchPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"deletePatchFile", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_deletePatchFile(PatchCoroPrxCallbackPtr callback,const std::string &app,const std::string &serverName,const std::string &patchFile,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"deletePatchFile", _os, context, _mStatus, callback, true);
        }

        tars::Int32 download(const std::string & file,tars::Int32 pos,vector<tars::Char> &vb,const std::map<std::string, std::string> &context = TARS_CONTEXT(),map<std::string, std::string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(file, 1);
            _os.write(pos, 2);
            _os.write(vb, 3);
            std::map<std::string, std::string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"download", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(vb, 3, true);
            return _ret;
        }

        void async_download(PatchPrxCallbackPtr callback,const std::string &file,tars::Int32 pos,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(file, 1);
            _os.write(pos, 2);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"download", _os, context, _mStatus, callback);
        }
        
        tars::Future< PatchPrxCallbackPromise::PromisedownloadPtr > promise_async_download(const std::string &file,tars::Int32 pos,const std::map<std::string, std::string>& context)
        {
            tars::Promise< PatchPrxCallbackPromise::PromisedownloadPtr > promise;
            PatchPrxCallbackPromisePtr callback = new PatchPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(file, 1);
            _os.write(pos, 2);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"download", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_download(PatchCoroPrxCallbackPtr callback,const std::string &file,tars::Int32 pos,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(file, 1);
            _os.write(pos, 2);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"download", _os, context, _mStatus, callback, true);
        }

        tars::Int32 listFileInfo(const std::string & path,vector<tars::FileInfo> &vf,const std::map<std::string, std::string> &context = TARS_CONTEXT(),map<std::string, std::string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(path, 1);
            _os.write(vf, 2);
            std::map<std::string, std::string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"listFileInfo", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(vf, 2, true);
            return _ret;
        }

        void async_listFileInfo(PatchPrxCallbackPtr callback,const std::string &path,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(path, 1);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"listFileInfo", _os, context, _mStatus, callback);
        }
        
        tars::Future< PatchPrxCallbackPromise::PromiselistFileInfoPtr > promise_async_listFileInfo(const std::string &path,const std::map<std::string, std::string>& context)
        {
            tars::Promise< PatchPrxCallbackPromise::PromiselistFileInfoPtr > promise;
            PatchPrxCallbackPromisePtr callback = new PatchPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(path, 1);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"listFileInfo", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_listFileInfo(PatchCoroPrxCallbackPtr callback,const std::string &path,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(path, 1);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"listFileInfo", _os, context, _mStatus, callback, true);
        }

        tars::Int32 preparePatchFile(const std::string & app,const std::string & serverName,const std::string & patchFile,std::string &result,const std::map<std::string, std::string> &context = TARS_CONTEXT(),map<std::string, std::string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            _os.write(result, 4);
            std::map<std::string, std::string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"preparePatchFile", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(result, 4, true);
            return _ret;
        }

        void async_preparePatchFile(PatchPrxCallbackPtr callback,const std::string &app,const std::string &serverName,const std::string &patchFile,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"preparePatchFile", _os, context, _mStatus, callback);
        }
        
        tars::Future< PatchPrxCallbackPromise::PromisepreparePatchFilePtr > promise_async_preparePatchFile(const std::string &app,const std::string &serverName,const std::string &patchFile,const std::map<std::string, std::string>& context)
        {
            tars::Promise< PatchPrxCallbackPromise::PromisepreparePatchFilePtr > promise;
            PatchPrxCallbackPromisePtr callback = new PatchPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"preparePatchFile", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_preparePatchFile(PatchCoroPrxCallbackPtr callback,const std::string &app,const std::string &serverName,const std::string &patchFile,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(patchFile, 3);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"preparePatchFile", _os, context, _mStatus, callback, true);
        }

        tars::Int32 upload(const std::string & app,const std::string & serverName,const tars::FileContent & content,const std::map<std::string, std::string> &context = TARS_CONTEXT(),map<std::string, std::string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(content, 3);
            std::map<std::string, std::string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"upload", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_upload(PatchPrxCallbackPtr callback,const std::string &app,const std::string &serverName,const tars::FileContent &content,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(content, 3);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"upload", _os, context, _mStatus, callback);
        }
        
        tars::Future< PatchPrxCallbackPromise::PromiseuploadPtr > promise_async_upload(const std::string &app,const std::string &serverName,const tars::FileContent &content,const std::map<std::string, std::string>& context)
        {
            tars::Promise< PatchPrxCallbackPromise::PromiseuploadPtr > promise;
            PatchPrxCallbackPromisePtr callback = new PatchPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(content, 3);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"upload", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_upload(PatchCoroPrxCallbackPtr callback,const std::string &app,const std::string &serverName,const tars::FileContent &content,const std::map<std::string, std::string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(serverName, 2);
            _os.write(content, 3);
            std::map<std::string, std::string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"upload", _os, context, _mStatus, callback, true);
        }

        PatchProxy* tars_hash(int64_t key)
        {
            return (PatchProxy*)ServantProxy::tars_hash(key);
        }

        PatchProxy* tars_consistent_hash(int64_t key)
        {
            return (PatchProxy*)ServantProxy::tars_consistent_hash(key);
        }

        PatchProxy* tars_set_timeout(int msecond)
        {
            return (PatchProxy*)ServantProxy::tars_set_timeout(msecond);
        }

        static const char* tars_prxname() { return "PatchProxy"; }
    };
    typedef tars::TC_AutoPtr<PatchProxy> PatchPrx;

    /* servant for server */
    class Patch : public tars::Servant
    {
    public:
        virtual ~Patch(){}
        virtual tars::Int32 deletePatchFile(const std::string & app,const std::string & serverName,const std::string & patchFile,tars::TarsCurrentPtr current) = 0;
        static void async_response_deletePatchFile(tars::TarsCurrentPtr current, tars::Int32 _ret)
        {
            if (current->getRequestVersion() == tars::TUPVERSION )
            {
                tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);

                std::vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == tars::JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 download(const std::string & file,tars::Int32 pos,vector<tars::Char> &vb,tars::TarsCurrentPtr current) = 0;
        static void async_response_download(tars::TarsCurrentPtr current, tars::Int32 _ret, const vector<tars::Char> &vb)
        {
            if (current->getRequestVersion() == tars::TUPVERSION )
            {
                tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);
                tarsAttr.put("vb", vb);

                std::vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == tars::JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["vb"] = tars::JsonOutput::writeJson(vb);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(vb, 3);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 listFileInfo(const std::string & path,vector<tars::FileInfo> &vf,tars::TarsCurrentPtr current) = 0;
        static void async_response_listFileInfo(tars::TarsCurrentPtr current, tars::Int32 _ret, const vector<tars::FileInfo> &vf)
        {
            if (current->getRequestVersion() == tars::TUPVERSION )
            {
                tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);
                tarsAttr.put("vf", vf);

                std::vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == tars::JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["vf"] = tars::JsonOutput::writeJson(vf);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(vf, 2);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 preparePatchFile(const std::string & app,const std::string & serverName,const std::string & patchFile,std::string &result,tars::TarsCurrentPtr current) = 0;
        static void async_response_preparePatchFile(tars::TarsCurrentPtr current, tars::Int32 _ret, const std::string &result)
        {
            if (current->getRequestVersion() == tars::TUPVERSION )
            {
                tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);
                tarsAttr.put("result", result);

                std::vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == tars::JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["result"] = tars::JsonOutput::writeJson(result);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(result, 4);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 upload(const std::string & app,const std::string & serverName,const tars::FileContent & content,tars::TarsCurrentPtr current) = 0;
        static void async_response_upload(tars::TarsCurrentPtr current, tars::Int32 _ret)
        {
            if (current->getRequestVersion() == tars::TUPVERSION )
            {
                tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);

                std::vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == tars::JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, std::vector<char> &_sResponseBuffer)
        {
            static ::std::string __tars__Patch_all[]=
            {
                "deletePatchFile",
                "download",
                "listFileInfo",
                "preparePatchFile",
                "upload"
            };

            std::pair<std::string*, std::string*> r = equal_range(__tars__Patch_all, __tars__Patch_all+5, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __tars__Patch_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string app;
                    std::string serverName;
                    std::string patchFile;
                    if (_current->getRequestVersion() == tars::TUPVERSION)
                    {
                        tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("app", app);
                        tarsAttr.get("serverName", serverName);
                        tarsAttr.get("patchFile", patchFile);
                    }
                    else if (_current->getRequestVersion() == tars::JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(app, _jsonPtr->value["app"], true);
                        tars::JsonInput::readJson(serverName, _jsonPtr->value["serverName"], true);
                        tars::JsonInput::readJson(patchFile, _jsonPtr->value["patchFile"], true);
                    }
                    else
                    {
                        _is.read(app, 1, true);
                        _is.read(serverName, 2, true);
                        _is.read(patchFile, 3, true);
                    }
                    tars::Int32 _ret = deletePatchFile(app,serverName,patchFile, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == tars::TUPVERSION)
                        {
                            tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == tars::JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string file;
                    tars::Int32 pos;
                    vector<tars::Char> vb;
                    if (_current->getRequestVersion() == tars::TUPVERSION)
                    {
                        tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("file", file);
                        tarsAttr.get("pos", pos);
                        tarsAttr.getByDefault("vb", vb, vb);
                    }
                    else if (_current->getRequestVersion() == tars::JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(file, _jsonPtr->value["file"], true);
                        tars::JsonInput::readJson(pos, _jsonPtr->value["pos"], true);
                        tars::JsonInput::readJson(vb, _jsonPtr->value["vb"], false);
                    }
                    else
                    {
                        _is.read(file, 1, true);
                        _is.read(pos, 2, true);
                        _is.read(vb, 3, false);
                    }
                    tars::Int32 _ret = download(file,pos,vb, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == tars::TUPVERSION)
                        {
                            tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.put("vb", vb);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == tars::JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["vb"] = tars::JsonOutput::writeJson(vb);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(vb, 3);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string path;
                    vector<tars::FileInfo> vf;
                    if (_current->getRequestVersion() == tars::TUPVERSION)
                    {
                        tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("path", path);
                        tarsAttr.getByDefault("vf", vf, vf);
                    }
                    else if (_current->getRequestVersion() == tars::JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(path, _jsonPtr->value["path"], true);
                        tars::JsonInput::readJson(vf, _jsonPtr->value["vf"], false);
                    }
                    else
                    {
                        _is.read(path, 1, true);
                        _is.read(vf, 2, false);
                    }
                    tars::Int32 _ret = listFileInfo(path,vf, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == tars::TUPVERSION)
                        {
                            tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.put("vf", vf);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == tars::JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["vf"] = tars::JsonOutput::writeJson(vf);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(vf, 2);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string app;
                    std::string serverName;
                    std::string patchFile;
                    std::string result;
                    if (_current->getRequestVersion() == tars::TUPVERSION)
                    {
                        tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("app", app);
                        tarsAttr.get("serverName", serverName);
                        tarsAttr.get("patchFile", patchFile);
                        tarsAttr.getByDefault("result", result, result);
                    }
                    else if (_current->getRequestVersion() == tars::JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(app, _jsonPtr->value["app"], true);
                        tars::JsonInput::readJson(serverName, _jsonPtr->value["serverName"], true);
                        tars::JsonInput::readJson(patchFile, _jsonPtr->value["patchFile"], true);
                        tars::JsonInput::readJson(result, _jsonPtr->value["result"], false);
                    }
                    else
                    {
                        _is.read(app, 1, true);
                        _is.read(serverName, 2, true);
                        _is.read(patchFile, 3, true);
                        _is.read(result, 4, false);
                    }
                    tars::Int32 _ret = preparePatchFile(app,serverName,patchFile,result, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == tars::TUPVERSION)
                        {
                            tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.put("result", result);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == tars::JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["result"] = tars::JsonOutput::writeJson(result);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(result, 4);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string app;
                    std::string serverName;
                    tars::FileContent content;
                    if (_current->getRequestVersion() == tars::TUPVERSION)
                    {
                        tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("app", app);
                        tarsAttr.get("serverName", serverName);
                        tarsAttr.get("content", content);
                    }
                    else if (_current->getRequestVersion() == tars::JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(app, _jsonPtr->value["app"], true);
                        tars::JsonInput::readJson(serverName, _jsonPtr->value["serverName"], true);
                        tars::JsonInput::readJson(content, _jsonPtr->value["content"], true);
                    }
                    else
                    {
                        _is.read(app, 1, true);
                        _is.read(serverName, 2, true);
                        _is.read(content, 3, true);
                    }
                    tars::Int32 _ret = upload(app,serverName,content, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == tars::TUPVERSION)
                        {
                            tars::UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == tars::JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
